Django/projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('pybo/ <int:question_id>/', views.detail, name='detail'),
    path('pybo/answer/create/ <int:question_id>/', views.answer_create, name='answer_create'),
]

Django/projects/mysite/pybo/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'pybo'

urlpatterns = [
     path('', views.index, name='index'),
     path('admin/', admin.site.urls),
     path('<int:question_id>/', views.detail, name='detail'),
     path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),
]

Django/projects/mysite/pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)  # 제목은 최대 200자까지
    content = models.TextField()  # 내용은 제한 없는 텍스트
    create_date = models.DateTimeField()  # 날짜 및 시간 정보 저장

    def __str__(self):
        return self.subject
    
class Answer(models.Model):  
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 기존 속성 연결 - ForeignKey
    # on_delete=models.CASCADE 이 답변이 연결된 질문이 삭제되면, 해당 답변도 함께 삭제됨. 

    content = models.TextField()
    create_date = models.DateTimeField()
    

Django/projects/mysite/pybo/views.py
# from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question

def index(request):
    question_list = Question.objects.order_by("-create_date")
    context = {'question_list' : question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get("content"), create_date=timezone.now())
    # 임의 변수 넣어서 save() 메서드 써도 됨
    return redirect('pybo:detail', question_id=question.id)

Django/projects/mysite/templates/pybo/question_detail.html
{% load static %}  <!-- 스태틱 파일 사용하려면 필요한 태그 -->
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}}">

<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ui>
        {% for answer in question.answer_set.all%}
        <li>{{answer.content}}</li>
    {% endfor %}
    </ui>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}  <!-- 웹 사이트 취약점 공격 방지 기술 (실제 웹 페이지에서 작성된 것인지 확인)-->
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="답변등록">
</form>

Django/projects/mysite/templates/pybo/question_list.html
{% if question_list %}  <!-- % : 템플릿 태그-->
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{%endif%}